#######################################################
#                                                     #
# SECURITY REMINDER: Never commit credentials to Git. #
#                                                     #
#######################################################
db:
    host: localhost
    user:
    password:
    dbname:
